[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd nanevida-backend && gunicorn nane.wsgi:application --bind 0.0.0.0:$PORT --workers 4"

[nixpacks]
nixPkgs = ["python39", "python39Packages.pip"]

[nixpacks.phases.install]
cmds = ["cd nanevida-backend && pip install -r requirements.txt"]

[nixpacks.phases.build]
cmds = ["cd nanevida-backend && python manage.py collectstatic --noinput"]
