[build]
builder = "NIXPACKS"
buildCommand = "cd nanevida-backend && pip install -r requirements.txt && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd nanevida-backend && gunicorn nane.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nixPkgs = ["python39"]
