[build]
builder = "nixpacks"
buildCommand = "cd nanevida-backend && pip install -r requirements.txt"

[deploy]
startCommand = "cd nanevida-backend && gunicorn nane.wsgi:application --bind 0.0.0.0:$PORT --workers 4"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
